### PR TITLE
Fix Auto generated config

### LINKED ISSUE #108: Docs: Auto generated config not working
@gastaldi i have stared at this but I don't know why AsciiDoc is not generating the `.adoc` for the `ReportConfig` object like it should?

### PR DESCRIPTION
**Pull request by gastaldi**
- Fixes #108

### CODE REVIEW

**Review by nderwin — APPROVED** [review]
Ran it locally and it generated the config docs as expected.

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
@gastaldi i compared it to Mailpit that is working is this something that changed?  do I need to update all my extensions for this pattern?

**Comment by gastaldi** [comment]
@melloware this is required when you bump to Quarkus 3.14+: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.14#publishing-the-config-documentation

**Comment by melloware** [comment]
Excellent i will update mine for that and also to do your Split Release Workflow trick!

**Comment by gastaldi** [comment]
I'll be sending PRs for the Split Release, as requested in https://github.com/quarkiverse/quarkiverse-devops/issues/275

**Comment by melloware** [comment]
Oh you rock!!!

**Pull request merged**
