### PR TITLE
Cleanup optional dependencies

### PR DESCRIPTION
**Pull request by gastaldi**
Some dependencies are already resolved transitively

### CODE REVIEW

**Comment by melloware** [comment]
I will be interested if these pass as without these I would get Native classloader failures?

**Review by melloware — CHANGES_REQUESTED** [review]
Yep native failed.

**Comment by melloware** [comment]
You can try adding them back 1 at a time. Saxon first.

**Comment by gastaldi** [comment]
Ah-ha, weird that the dependency is marked as optional but it is required. I think a substitution may be interesting here. Let me see what I can do

**Comment by melloware** [comment]
Yep I think we can do some clever things!  I always like starting with a working native build then I know when I break stuff as we try and trim it down.

**Comment by gastaldi** [comment]
Closing this for now

**Pull request closed without merging**
